#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
bspc rule -a Thunar state=floating

~/.config/bspwm/start-apps.sh

