#!/bin/sh

# TODO: redistribute workspaces when connecting monitors
bspc monitor -d I II III IV V VI VII VIII
#bspc monitor eDP1 -d I II III IV
#bspc monitor DP1 -d V VI VII VIII

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config border_width                0
bspc config window_gap                  12

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config focus_follows_pointer       true

bspc rule -a Zathura state=tiled
bspc rule -a Thunar state=floating rectangle 600x900

~/.config/bspwm/start-apps.sh

